# Generated by Django 3.2.3 on 2021-09-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('index', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='索引')),
                ('title', models.CharField(max_length=40, verbose_name='题目')),
                ('content', models.TextField(verbose_name='内容')),
                ('poster', models.CharField(default='游客', max_length=20, verbose_name='发帖人')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
                ('operator', models.CharField(default='', max_length=10, verbose_name='操作人')),
            ],
            options={
                'verbose_name_plural': '帖子表',
                'db_table': 'posting',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=4, verbose_name='性别')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('keshi', models.CharField(max_length=50, verbose_name='科室')),
                ('duty', models.CharField(max_length=20, verbose_name='职务')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
                ('ud_operator', models.CharField(max_length=10, verbose_name='操作人')),
                ('is_spuser', models.BooleanField(default=False, verbose_name='超级用户')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('index', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='索引')),
                ('content', models.TextField(verbose_name='评论')),
                ('poster', models.CharField(default='游客', max_length=20, verbose_name='评论人')),
                ('floor', models.IntegerField(default=0, verbose_name='楼层')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
                ('operator', models.CharField(max_length=10, verbose_name='操作人')),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbsapp.posting')),
            ],
            options={
                'verbose_name_plural': '评论表',
                'db_table': 'comments',
            },
        ),
    ]
