# Generated by Django 3.2.3 on 2021-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='content_digest',
            field=models.CharField(default='', max_length=40, verbose_name='内容摘要'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='operator',
            field=models.CharField(max_length=10, null=True, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='poster',
            field=models.CharField(max_length=10, null=True, verbose_name='发帖人'),
        ),
    ]
