# Generated by Django 3.2.3 on 2021-07-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0003_auto_20210729_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='poster',
            field=models.CharField(default='游客', max_length=10, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='operator',
            field=models.CharField(default='', max_length=10, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='poster',
            field=models.CharField(default='游客', max_length=10, verbose_name='发帖人'),
        ),
    ]
