# Generated by Django 3.2.3 on 2021-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0004_auto_20210730_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='poster',
            field=models.CharField(default='游客', max_length=20, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='poster',
            field=models.CharField(default='游客', max_length=20, verbose_name='发帖人'),
        ),
    ]
