# Generated by Django 3.2.3 on 2021-08-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0005_auto_20210803_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='楼层'),
        ),
    ]
