# Generated by Django 3.2.3 on 2021-08-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0006_comments_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='content_digest',
        ),
    ]
